### ISSUE TITLE
The last stable release has error with dispatchMessage()

### ISSUE THREAD

**Issue by bvoronov** [stanislav-web/ZF2-PHP-WebSocket-Server-Factory#5]
Take a look on [this statment](https://github.com/stanislav-web/ZF2-PHP-WebSocket-Server-Factory/blob/master/src/WebSockets/Service/WebsocketServer.php#L402). In the dev version it is correct and in the latest release is not.

**Comment by stanislav-web** [comment]
I fixed this . Try to lauch
